AWSTemplateFormatVersion: 2010-09-09
Parameters:
    Instancetype:
        Description: EC2 instance type selection
        Type: String
        Default: t2.micro
        AllowedValues: 
            - t2.micro
            - t2.medium
            - t2.small
            - m4.large
    
Resources:
    NewKeyPair:
        Type: AWS::EC2::KeyPair
        Properties:
            KeyName: MyTrialkeyPair
    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-00c39f71452c08778
            InstanceType: !Ref Instancetype
            KeyName: !Ref NewKeyPair
            SubnetId: !Ref MySubnet
            IamInstanceProfile: amazonec2roleforssm
            SecurityGroupIds:
                - Fn::GetAtt : InstanceSecurityGroup.GroupId
                - Fn::GetAtt : InstanceHTTPSecurityGroup.GroupId
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    sudo yum update -y
                    sudo yum install -y httpd
                    sudo systemctl start httpd
                    sudo systemctl enable httpd
                    echo "hello, how are, khana kha ke jaana han?" >> /var/www/html/index.html
    
    MyVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsSupport: 'true'
            EnableDnsHostnames: 'true'
            
    MySubnet:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref MyVPC
            CidrBlock: 10.0.0.0/24
            AvailabilityZone: "us-east-1a"
        
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable SSH via port 22
        VpcId: !Ref MyVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0

    InstanceHTTPSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable HTTP via port 80
            VpcId: !Ref MyVPC
            SecurityGroupIngress:
                - CidrIp: 0.0.0.0/0
                  IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  
    MyInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
            - Key: stack
              Value: trial
              
    AttachGateway:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: 
                Ref: MyVPC
            InternetGatewayId: 
                Ref: MyInternetGateway
                
    myEIP:
            Type: AWS::EC2::EIP
            Properties:
                InstanceId: !Ref EC2Instance
     
    
Outputs:
    InstanceID:
        Description: Instacne ID of the instance created
        Value: !Ref EC2Instance
    PublicDNS:
        Description: Get public DNS name
        Value: !GetAtt
                - EC2Instance
                - PublicDnsName
    PublicIP:
        Description: Get public IP address
        Value: !GetAtt
                - EC2Instance
                - PublicIp
